language: ruby
rvm:
- 2.0.0
bundler_args: --without development production
notifications:
  email:
  - me@svenfuchs.com
  - joneslee85@gmail.com
  notifications:
    irc:
    - irc.freenode.net#rgsoc
before_install:
- gem install bundler
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create db:schema:load RAILS_ENV=test
script:
- bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: ES0VxL9vi6rnj2DQQSHiqtOTk0zvU/j0hxj64fSe3J/BIal+bkNSei6LTAfBlmDTp15gTJ8rVVif9+cS1TdXEnmxIdjFooiX9CrNtV93Vn96h6Wtey4owQyvQ6u6DVYTMOAI08/6f40QBy4po4H2gWvHUhtv5R4a+S85o/zhlac=
  app: rgsoc-teams
  on:
    repo: rails-girls-summer-of-code/rgsoc-teams
